global using Microsoft.EntityFrameworkCore;
global using e_shop_backend.Models.Response;
global using e_shop_backend.Config;
global using e_shop_backend.Repositories;
global using e_shop_backend.Models.ProductModel;
global using e_shop_backend.Models.Request;
global using e_shop_backend.Core.Configuration;
global using Microsoft.AspNetCore.Mvc;
global using e_shop_backend.Core.Repositories.ProductRepository;
global using Microsoft.Extensions.Logging;
global using System.Reflection;
global using static Microsoft.EntityFrameworkCore.DbLoggerCategory;